/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package mypkg;

import util.Greeter;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;

import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.RealMatrix;


public class App {

    private static final Logger logger = LogManager.getLogger();

    
//     public String getGreeting() {
//         return "Hello world.";
//     }

    public static void main(String[] args) {

        Configurator.setLevel(logger.getName(), Level.TRACE);
        logger.info("Entering application.");
	
//         System.out.println(new App().getGreeting());
        Greeter.greeter("greeter() called to print: entering application");

        logger.info("Calling doMatrixStuff()");
        doMatrixStuff();

        logger.info("Exiting application.");
        Greeter.greeter("greeter() called to print: exiting application");

    }

    private static void doMatrixStuff() {
	logger.info("Apache Commons Math3.");

        double[][] m1_data = new double[][] {
                new double[]{1d, 5d},
                new double[]{2d, 3d},
                new double[]{1d, 7d}
        };
        double[][] m2_data = new double[][]{
                new double[]{1d, 2d, 3d, 7d},
                new double[]{5d, 2d, 8d, 1d}
        };
        RealMatrix m1 = new Array2DRowRealMatrix(m1_data);
        RealMatrix m2 = new Array2DRowRealMatrix(m2_data);
        RealMatrix resultMatrix = m1.multiply(m2);
        System.out.println("matrix product: " + resultMatrix);
    }
}
